### ISSUE TITLE
Could not pass event PlayerInteractEntityEvent

### ISSUE THREAD

**Issue by VirtualPlanetNT** [PYRRH4/PyrCore#6]
### Issue description
When player use right click in entity, I get this error in console.
https://pastebin.com/2UwtkJ8x

### Versions

Spigot : PaperSpigot 1.8.8

PyrCore : 6.3.1

**Comment by DjeyMute** [comment]
Same for me : 
16.02 14:44:38 [Server] ERROR Could not pass event PlayerInteractEntityEvent to PyrCore v6.3.1
16.02 14:44:38 [Server] INFO org.bukkit.event.EventException: null
16.02 14:44:38 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1976) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_162]
16.02 14:44:38 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-506]
16.02 14:44:38 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
16.02 14:44:38 [Server] INFO Caused by: java.lang.ClassCastException: net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC$PlayerNPC cannot be cast to org.bukkit.entity.Cow
16.02 14:44:38 [Server] INFO at be.pyrrh4.pyrcore.PyrCore.event(PyrCore.java:328) ~[?:?]
16.02 14:44:38 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor125.execute(Unknown Source) ~[?:?]
16.02 14:44:38 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-506]

**Comment by Dreandor** [comment]
Same issue
[20:22:22] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to PyrCore v6.3.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1809) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC$PlayerNPC cannot be cast to org.bukkit.entity.Cow
	at be.pyrrh4.pyrcore.PyrCore.event(PyrCore.java:328) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	... 15 more
[20:22:22] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to PyrCore v6.3.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1809) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
